FROM mariadb

# Variables de entorno para la configuración de MariaDB (ajusta según tus necesidades)
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword
